name: pharma_bros
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  get: ^4.6.6                             # for use getx
  http: ^1.2.0                            # for use http
  cached_network_image: ^3.3.1            # for use cached_network_image
  path_provider: ^2.1.3                   # for use cached_network_image
  flutter_svg: ^2.0.10+1                  # for use svg image
  vibration: ^1.8.4                       # for use vibration when pressed button
  device_info_plus: ^9.1.2                # for use device info   
  url_launcher: ^6.1.8                    # for web view


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: NotoSansKR-Light
    fonts:
      - asset: assets/fonts/NotoSansKR-Light.ttf

  - family: NotoSansKR-Regular
    fonts:
      - asset: assets/fonts/NotoSansKR-Regular.ttf

  - family: NotoSansKR-Medium
    fonts:
      - asset: assets/fonts/NotoSansKR-Medium.ttf
